// 本机游戏库（由小台扫描生成，非手写）。
// 游戏架点「导入本机游戏库」按钮时，把这些条目合并进用户 localStorage（按 id 去重，不覆盖已有）。
// - Steam 游戏：带 appid，启动走 steam://rungameid/<appid>（需 Steam 客户端运行）；lastLaunch 来自 Steam localconfig.vdf 的 LastPlayed（官方最后游玩时间）
// - 非 Steam 游戏：带 exe，启动走 wbexec:// 协议（需本机注册 &lt;本机 wbexec 注册表项&gt;）；lastLaunch 取 exe 文件修改时间兜底（lastLaunchSrc='exe-mtime'）
// 游戏架渲染时按 lastLaunch 自动分类：≤7天在玩 / 8-30天待回归 / 31-90天暂停 / >90天弃坑；无 lastLaunch 时退回 status 手动值。
window.SCANNED_GAMES = [
  { id:"steam-2704110", name:"Aliya: Timelink", appid:2704110, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/2704110/library_600x900.jpg", emoji:"🎮", status:"playing", lastLaunch:1786775868000, lastLaunchSrc:"steam", note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-3041090", name:"Aliya: Timelink Art Collection", appid:3041090, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/3041090/library_600x900.jpg", emoji:"🎮", status:"abandoned", lastLaunch:1735911933000, lastLaunchSrc:"steam", note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-945360", name:"Among Us", appid:945360, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/945360/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-1612100", name:"Big Earth", appid:1612100, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/1612100/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-1982340", name:"Blanc", appid:1982340, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/1982340/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-1360390", name:"Cats and the Other Lives", appid:1360390, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/1360390/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-894020", name:"Death's Door", appid:894020, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/894020/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-1222140", name:"Detroit: Become Human", appid:1222140, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/1222140/library_600x900.jpg", emoji:"🎮", status:"playing", lastLaunch:1786785961000, lastLaunchSrc:"steam", note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-382310", name:"Eco", appid:382310, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/382310/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-1080020", name:"Electrician Simulator", appid:1080020, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/1080020/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-392110", name:"ENDLESS™ Space 2", appid:392110, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/392110/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-22380", name:"Fallout: New Vegas", appid:22380, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/22380/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-1570010", name:"FAR: Changing Tides", appid:1570010, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/1570010/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-322170", name:"Geometry Dash", appid:322170, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/322170/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-1496790", name:"Gotham Knights", appid:1496790, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/1496790/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-365450", name:"Hacknet", appid:365450, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/365450/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:1786022296000, lastLaunchSrc:"steam", note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-612210", name:"Hacknet - Labyrinths Official Soundtrack", appid:612210, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/612210/library_600x900.jpg", emoji:"🎮", status:"abandoned", lastLaunch:1750853031000, lastLaunchSrc:"steam", note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-408710", name:"Hacknet Official Soundtrack", appid:408710, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/408710/library_600x900.jpg", emoji:"🎮", status:"abandoned", lastLaunch:1750853027000, lastLaunchSrc:"steam", note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-903950", name:"Last Oasis", appid:903950, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/903950/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-2381590", name:"Only Up!", appid:2381590, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/2381590/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-842180", name:"Prison Simulator", appid:842180, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/842180/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-578080", name:"PUBG: BATTLEGROUNDS", appid:578080, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/578080/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:1785853945000, lastLaunchSrc:"steam", note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-312520", name:"Rain World", appid:312520, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/312520/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-283640", name:"Salt and Sanctuary", appid:283640, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/283640/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-1286580", name:"Ship of Fools", appid:1286580, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/1286580/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-207140", name:"SpeedRunners", appid:207140, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/207140/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-1716740", name:"Starfield", appid:1716740, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-1283400", name:"Steelrising", appid:1283400, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/1283400/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-970560", name:"STEINS;GATE: My Darling's Embrace", appid:970560, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/970560/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:1785856141000, lastLaunchSrc:"steam", note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-391540", name:"Undertale", appid:391540, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/391540/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"steam-431960", name:"Wallpaper Engine", appid:431960, cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/431960/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:1786114498000, lastLaunchSrc:"steam", note:"Steam 库（steam:// 启动）", planBack:"", addedAt:Date.now() },
  { id:"ext-pvzhe", name:"植物大战僵尸杂交版", exe:"", cover:"", emoji:"🎮", status:"abandoned", lastLaunch:1720155923815, lastLaunchSrc:"exe-mtime", note:"非 Steam 独立游戏（exe 直启）", planBack:"", addedAt:Date.now() },
  { id:"ext-miniworld", name:"官方版迷你世界", exe:"", cover:"", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"非 Steam 独立游戏（exe 直启，迷你世界.exe 已更名 iworldpc.exe）", planBack:"", addedAt:Date.now() },
  { id:"ext-amongus", name:"Among Us（绿色版）", exe:"", cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/945360/library_600x900.jpg", emoji:"🎮", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"绿色版，非 Steam（exe 直启）", planBack:"", addedAt:Date.now() },
  { id:"ext-catquest3", name:"Cat Quest III 猫猫任务3", exe:"", cover:"https://cdn.cloudflare.steamstatic.com/steam/apps/2305840/library_600x900.jpg", emoji:"🐱", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"绿色版，非 Steam（exe 直启）", planBack:"", addedAt:Date.now() },
  { id:"ext-fevergames", name:"网易发烧游戏 · 我的世界", exe:"", cover:"", emoji:"⛏️", status:"backlog", lastLaunch:null, lastLaunchSrc:null, note:"网易我的世界中国版（exe 直启）", planBack:"", addedAt:Date.now() }
];
