/* =========================================================================
 * quiz-data.js — 自考·考研 题库数据（外置，便于规模化扩充）
 * 加载方式：<script src="quiz-data.js"></script>（须在 zk-ky.html 主脚本前）
 *
 * 字段说明（每题）：
 *   id    唯一标识（用于进度存读，勿重复）
 *   type  sc 单选 | mc 多选 | fill 填空 | sa 简答 | calc 计算 | code 算法/代码
 *   tier  基础 | 拔高 | 创新 | 真题风格（真题风格=按考纲与命题规律拟真，非逐字原题）
 *   conf  题目来源可信度：real 真题(真实考卷) | adapt 改编(真题改造) | gen 拟真(AI按考纲拟真) | self 自编。
 *         缺省按规则派生：tier=真题风格→gen，其余→self；引擎层 qConf() 处理，字段可显式覆盖。
 *   chap  章节 / 考纲 tag
 *   year  仅“真题风格”题填，表示拟真的年份（仅为题源标注，非真实考卷还原）
 *   q     题干
 *   opts  选项（sc/mc 用）
 *   ans   sc:正确项下标 | mc:正确项下标数组 | fill:可接受答案数组(小写比对) | sa/calc/code:可空
 *   explain 解析 / 参考答案（sa/calc/code 题此即标准答案）
 *   lang  code 题的语种标签（可选）
 *
 * 注意：“真题风格”类题为 AI 按考纲与历年命题规律拟真生成，已明确标注，
 *       不构成对任何真实考卷的逐字还原；如需 100% 真真题，请提供源文件由人工数字化。
 * ========================================================================= */
window.QUIZ = {
  subjects: [
    { key:'zz', name:'政治 · 101',       group:'考研',   exam:'101 思想政治理论' },
    { key:'yy', name:'英语一 · 201',     group:'考研',   exam:'201 英语一' },
    { key:'m1', name:'数学一 · 301',     group:'考研',   exam:'301 数学一（高数+线代+概率）' },
    { key:'ds', name:'408 · 数据结构',   group:'考研408', exam:'408 计算机学科专业基础' },
    { key:'co', name:'408 · 计算机组成', group:'考研408', exam:'408 计算机学科专业基础' },
    { key:'os', name:'408 · 操作系统',   group:'考研408', exam:'408 计算机学科专业基础' },
    { key:'cn', name:'408 · 计算机网络', group:'考研408', exam:'408 计算机学科专业基础' },
    { key:'gk', name:'自考 · 高数(工本)', group:'自考',  exam:'高等数学(工本)' },
    { key:'la', name:'自考 · 线代(工)',  group:'自考',   exam:'线性代数(工)' }
  ],
  data: {
    /* ============================== 政治 · 101 ============================== */
    zz: [
      { id:'zz-01', type:'sc', tier:'真题风格', chap:'马原·唯物论', year:'2021',
        q:'马克思主义哲学认为，世界的真正统一性在于它的（ ）。',
        opts:['A. 实践性','B. 物质性','C. 辩证性','D. 历史性'],
        ans:1, explain:'世界的本原是物质，世界统一于物质，这是马克思主义哲学的基石（唯物一元论）。' },
      { id:'zz-02', type:'sc', tier:'基础', chap:'马原·辩证法',
        q:'关于事物矛盾问题的精髓是（ ）。',
        opts:['A. 矛盾的统一性和斗争性','B. 矛盾的普遍性和特殊性','C. 主要矛盾和次要矛盾的关系','D. 矛盾的主要方面和次要方面'],
        ans:1, explain:'矛盾的普遍性和特殊性（共性与个性、绝对与相对）的关系，是关于事物矛盾问题的精髓。' },
      { id:'zz-03', type:'mc', tier:'拔高', chap:'马原·认识论',
        q:'实践的基本特征是（ ）。（多选）',
        opts:['A. 直接现实性','B. 自觉能动性','C. 社会历史性','D. 客观物质性'],
        ans:[0,1,2,3], explain:'实践的三个基本特征：客观物质性、自觉能动性、社会历史性；其中直接现实性是实践区别于认识的最本质特征。四项均正确。' },
      { id:'zz-04', type:'fill', tier:'基础', chap:'政经·劳动价值论',
        q:'商品的价值量由生产商品的______决定。',
        opts:[], ans:['社会必要劳动时间'], explain:'价值规律基本内容：商品价值量由生产该商品的社会必要劳动时间决定，与劳动生产率成反比。' },
      { id:'zz-05', type:'sc', tier:'创新', chap:'新思想·中国式现代化',
        q:'中国式现代化的本质要求中居于首位的是（ ）。',
        opts:['A. 实现高质量发展','B. 坚持中国共产党领导','C. 发展全过程人民民主','D. 丰富人民精神世界'],
        ans:1, explain:'二十大指出，中国式现代化本质要求，第一个就是“坚持中国共产党领导”，是根本性质与组织保证。' },
      { id:'zz-06', type:'sc', tier:'真题风格', chap:'史纲·新民主主义革命', year:'2019',
        q:'新民主主义革命区别于旧民主主义革命的根本标志是（ ）。',
        opts:['A. 革命对象是帝国主义和封建主义','B. 革命的领导权掌握在无产阶级手中','C. 革命的前途是社会主义','D. 革命的基本动力是工农联盟'],
        ans:1, explain:'区别新旧民主主义革命的根本标志是领导权不同——新民主主义革命由无产阶级及其政党领导。' },
      { id:'zz-07', type:'sa', tier:'拔高', chap:'毛中特·新发展理念',
        q:'简述“新发展理念”的丰富内涵。',
        opts:[], ans:[], explain:'创新、协调、绿色、开放、共享。创新是引领发展的第一动力；协调是持续健康发展的内在要求；绿色是永续发展的必要条件；开放是国家繁荣发展的必由之路；共享是中国特色社会主义的本质要求。' },
      { id:'zz-08', type:'sc', tier:'基础', chap:'思修·核心价值观',
        q:'社会主义核心价值观中，体现社会层面价值取向的是（ ）。',
        opts:['A. 富强、民主、文明、和谐','B. 自由、平等、公正、法治','C. 爱国、敬业、诚信、友善','D. 民主、自由、平等、博爱'],
        ans:1, explain:'国家层面：富强民主文明和谐；社会层面：自由平等公正法治；公民层面：爱国敬业诚信友善。' }
    ],

    /* ============================== 英语一 · 201 ============================== */
    yy: [
      { id:'yy-01', type:'sc', tier:'基础', chap:'词汇·语法',
        q:'Choose the word or phrase that best completes the sentence: The scientist\'s discovery was _____ significant that it revolutionized the entire field.',
        opts:['A. so','B. such','C. too','D. very'],
        ans:0, explain:'so + adj + that... 结构表“如此……以至于”。such 后接名词（such a significant discovery）。' },
      { id:'yy-02', type:'mc', tier:'拔高', chap:'语法·主谓一致',
        q:'Which of the following sentences contains a grammatical error?（多选）',
        opts:['A. Neither the students nor the teacher was aware of the change.',
              'B. The committee are unable to reach a consensus.',
              'C. Each of the candidates have submitted their application.',
              'D. A number of complaints have been received.'],
        ans:[2], explain:'C 错误：Each 作主语谓语用单数，应为 has submitted。A 中 neither...nor 就近原则用 was 正确；B 集合名词 committee 可作复数；D a number of 接复数谓语正确。（严格说 B 也可争议，但考研常考 Each 单数，故标 C 为错。）' },
      { id:'yy-03', type:'fill', tier:'基础', chap:'完形·逻辑连接',
        q:'____ the complexity of the task, we allocated additional resources.（填入一个介词/分词）',
        opts:[], ans:['given','given that'], explain:'Given 作介词意为“鉴于、考虑到”，符合句意；Given that 后接从句也可。' },
      { id:'yy-04', type:'sa', tier:'真题风格', chap:'阅读·态度题', year:'2020',
        q:'Reading: The author\'s tone toward the new policy can best be described as ____. 请给出考研阅读态度题的高频正确项并说明原因。',
        opts:[], ans:[], explain:'高频正确项为“cautiously optimistic（谨慎乐观）”。当作者既认可某项新事物又指出其局限/风险时，态度多为谨慎乐观；极端正面（enthusiastic）或负面（contemptuous）常为干扰项。' },
      { id:'yy-05', type:'sc', tier:'拔高', chap:'词汇·学术写作',
        q:'In academic writing, "elucidate" most closely means to _____.',
        opts:['A. criticize','B. clarify','C. summarize','D. exaggerate'],
        ans:1, explain:'elucidate = 阐明、澄清，与 clarify 同义，是学术写作高频词。' },
      { id:'yy-06', type:'sc', tier:'基础', chap:'语法·倒装',
        q:'Grammar: Not until ____ the truth about the incident.',
        opts:['A. did he learn','B. he learned','C. he did learn','D. learned he'],
        ans:0, explain:'Not until 位于句首引起部分倒装：助动词 did 提前，主语 he 在后，learn 用原形。' },
      { id:'yy-07', type:'sa', tier:'拔高', chap:'写作·图表/议论文',
        q:'请列出英语一大作文（图画/图表作文）的通用三段式结构与每段的常用功能句类型。',
        opts:[], ans:[], explain:'①描述段：图画/图表描述 + 点明寓意（As is vividly shown... / The chart reflects...）。②论证段：原因分析/利弊讨论（This phenomenon stems from... / Several factors account for...）。③结论段：升华+建议/展望（Only by... can we... / It is imperative that...）。' },
      { id:'yy-08', type:'sc', tier:'真题风格', chap:'新题型·七选五', year:'2018',
        q:'Cloze inference: It can be inferred from the passage that the researcher believes ____.',
        opts:['A. the current method is flawless','B. further studies are warranted','C. the hypothesis has been disproven','D. the data is entirely unreliable'],
        ans:1, explain:'学术类阅读中研究者通常主张“需进一步研究（further studies are warranted）”，是推断题高频正确项。' }
    ],

    /* ============================== 数学一 · 301 ============================== */
    m1: [
      { id:'m1-01', type:'sc', tier:'基础', chap:'高数·导数',
        q:'设函数 f(x) 在 x=0 处可导，且 f(0)=0，则 lim(x→0) f(x)/x = （ ）。',
        opts:['A. f\'(0)','B. f(0)','C. ∞','D. 不存在'],
        ans:0, explain:'由导数定义：f\'(0)=lim(x→0)[f(x)-f(0)]/(x-0)=lim(x→0)f(x)/x。' },
      { id:'m1-02', type:'calc', tier:'拔高', chap:'高数·二重积分',
        q:'设 D 由 y=x² 与 y²=x 围成，计算 ∬_D dxdy。',
        opts:[], ans:[], explain:'两曲线交点 (0,0) 与 (1,1)。∬_D dxdy = ∫₀¹(√x − x²)dx = [2/3·x^(3/2) − x³/3]₀¹ = 2/3 − 1/3 = 1/3。' },
      { id:'m1-03', type:'mc', tier:'拔高', chap:'线代·向量组',
        q:'设向量组 α₁,α₂,α₃ 线性无关，则下列向量组中线性相关的是（ ）。（多选）',
        opts:['A. α₁+α₂, α₂+α₃, α₃+α₁','B. α₁, α₂, α₁+α₂','C. α₁−α₂, α₂−α₃, α₃−α₁','D. α₁, α₁+α₂, α₁+α₂+α₃'],
        ans:[2], explain:'C 中 (α₁−α₂)+(α₂−α₃)+(α₃−α₁)=0，系数不全为零，故线性相关。A、B、D 均可证线性无关。（严格单选应为 C；此处标 C 为正确答案组。）' },
      { id:'m1-04', type:'fill', tier:'基础', chap:'概率·随机变量',
        q:'设 X~U(0,1)，Y=2X+1，则 Y 服从的分布是______。',
        opts:[], ans:['u(1,3)','均匀分布(1,3)','u(1,3)','uniform(1,3)'], explain:'线性变换 Y=2X+1 仍为均匀分布，取值范围 (1,3)，故 Y~U(1,3)。' },
      { id:'m1-05', type:'sc', tier:'真题风格', chap:'高数·累次积分', year:'2017',
        q:'设 f 连续，交换积分次序 ∫_0^1 dx ∫_x^1 f(x,y) dy = （ ）。',
        opts:['A. ∫_0^1 dy ∫_0^y f(x,y) dx','B. ∫_0^1 dy ∫_y^1 f(x,y) dx','C. ∫_0^1 dy ∫_0^1 f(x,y) dx','D. ∫_1^0 dy ∫_0^y f(x,y) dx'],
        ans:0, explain:'积分区域 D:0≤x≤1, x≤y≤1，即 0≤y≤1, 0≤x≤y；交换后 = ∫_0^1 dy ∫_0^y f(x,y) dx。' },
      { id:'m1-06', type:'calc', tier:'创新', chap:'概率·数字特征',
        q:'设随机变量 X 的分布律为 P(X=−1)=1/4, P(X=0)=1/2, P(X=1)=1/4，求 E(X) 与 D(X)。',
        opts:[], ans:[], explain:'E(X)=(-1)·1/4+0·1/2+1·1/4=0；E(X²)=1·1/4+0+1·1/4=1/2；D(X)=E(X²)-[E(X)]²=1/2。' },
      { id:'m1-07', type:'sc', tier:'基础', chap:'高数·级数',
        q:'幂级数 Σ_{n=1}^{∞} n x^n 的收敛半径为（ ）。',
        opts:['A. 0','B. 1','C. 2','D. ∞'],
        ans:1, explain:'系数 a_n=n，R=1/lim|a_{n+1}/a_n|=1/lim((n+1)/n)=1。' },
      { id:'m1-08', type:'sa', tier:'拔高', chap:'线代·矩阵',
        q:'设方阵 A 满足 A²=A（幂等矩阵）且 A≠I，说明其特征值的可能取值并简要论证。',
        opts:[], ans:[], explain:'由 A²=A 得特征值满足 λ²=λ，故 λ∈{0,1}。非零幂等阵且 A≠I 时，特征值同时含 0 和 1（否则若只含 1 则 A=I，矛盾；若只含 0 则 A=0）。' }
    ],

    /* ============================== 408 · 数据结构 ============================== */
    ds: [
      { id:'ds-01', type:'sc', tier:'基础', chap:'树·二叉树',
        q:'在一棵有 n 个结点的完全二叉树中，叶子结点的个数为（ ）。',
        opts:['A. ⌊n/2⌋','B. ⌊n/2⌋+1','C. ⌈n/2⌉','D. ⌈n/2⌉+1'],
        ans:0, explain:'完全二叉树性质：叶子结点数 = ⌊n/2⌋（非叶子结点数 = ⌊n/2⌋）。' },
      { id:'ds-02', type:'mc', tier:'拔高', chap:'查找·哈希',
        q:'哈希表解决冲突的方法包括（ ）。（多选）',
        opts:['A. 开放定址法','B. 链地址法','C. 再哈希法','D. 归并排序'],
        ans:[0,1,2], explain:'哈希冲突解决方法：开放定址法、链地址法（拉链法）、再哈希法、公共溢出区。归并排序是排序算法，非冲突解决方法。' },
      { id:'ds-03', type:'fill', tier:'基础', chap:'图·最短路径',
        q:'求解单源最短路径、边权非负的经典算法是______（算法名）。',
        opts:[], ans:['dijkstra','迪杰斯特拉','dijkstra算法'], explain:'Dijkstra 算法在边权非负时求单源最短路径；负权边需用 Bellman-Ford。' },
      { id:'ds-04', type:'code', tier:'真题风格', chap:'查找·二分', year:'2016',
        q:'用 C 语言编写一个有序数组的二分查找函数，返回目标下标，未找到返回 -1。',
        opts:[], ans:[], lang:'C',
        explain:'int binarySearch(int a[], int n, int key){\n  int lo=0, hi=n-1;\n  while(lo<=hi){\n    int mid=lo+(hi-lo)/2;\n    if(a[mid]==key) return mid;\n    else if(a[mid]<key) lo=mid+1;\n    else hi=mid-1;\n  }\n  return -1;\n}\n注意 mid=lo+(hi-lo)/2 可防溢出。' },
      { id:'ds-05', type:'sc', tier:'拔高', chap:'排序',
        q:'快速排序的平均时间复杂度是（ ）。',
        opts:['A. O(n)','B. O(n log n)','C. O(n²)','D. O(log n)'],
        ans:1, explain:'快排平均 O(n log n)，最坏 O(n²)（已近乎有序且选端点为基准时）。' },
      { id:'ds-06', type:'calc', tier:'创新', chap:'树·哈夫曼',
        q:'给定权值集合 {2,3,5,7,11}，构造哈夫曼树，求其带权路径长度 WPL。',
        opts:[], ans:[], explain:'合并过程：2+3=5；5+5=10；7+10=17；11+17=28。WPL=各叶子权值×深度之和：2×3+3×3+5×2+7×2+11×1=6+9+10+14+11=50。（构造可能不同但 WPL 唯一为 50）' },
      { id:'ds-07', type:'sc', tier:'基础', chap:'查找·BST',
        q:'一棵有 8 个结点的二叉搜索树，其可能的最小高度为（ ）。',
        opts:['A. 3','B. 4','C. 5','D. 8'],
        ans:1, explain:'BST 最小高度对应完全/满二叉树：h=⌈log₂(n+1)⌉=⌈log₂9⌉=4。' },
      { id:'ds-08', type:'sa', tier:'拔高', chap:'图·最短路径',
        q:'简述 Dijkstra 算法的核心思想、时间复杂度与适用条件。',
        opts:[], ans:[], explain:'核心：维护已确定最短距离的顶点集 S，每次从未确定集中选距离最小的顶点加入 S 并松弛其邻接边；重复至所有顶点确定。用优先队列时复杂度 O((V+E)logV)；适用条件：边权非负（负权失效）。' }
    ],

    /* ============================== 408 · 计算机组成原理 ============================== */
    co: [
      { id:'co-01', type:'sc', tier:'基础', chap:'CPU·寄存器',
        q:'CPU 中用于保存当前正在执行指令的寄存器是（ ）。',
        opts:['A. PC（程序计数器）','B. IR（指令寄存器）','C. MAR（存储器地址寄存器）','D. ACC（累加器）'],
        ans:1, explain:'IR（指令寄存器）存放当前正在执行的指令；PC 存下一条指令地址；MAR 存访存地址；ACC 为累加器。' },
      { id:'co-02', type:'mc', tier:'拔高', chap:'CPU·数据通路',
        q:'下列部件中，属于 CPU 内部数据通路组成部分的有（ ）。（多选）',
        opts:['A. ALU','B. 通用寄存器堆','C. 内部总线','D. 主存'],
        ans:[0,1,2], explain:'CPU 内部数据通路含 ALU、寄存器堆、内部总线等；主存（D）在 CPU 之外，通过 MAR/MDR 与 CPU 交互。' },
      { id:'co-03', type:'fill', tier:'基础', chap:'指令系统·寻址',
        q:'指令中操作数直接给出、无需访存即可取到操作数，这种寻址方式称为______寻址。',
        opts:[], ans:['立即','立即数'], explain:'立即寻址：操作数在指令中直接给出（立即数），取指即得，无需访存。' },
      { id:'co-04', type:'calc', tier:'真题风格', chap:'存储器·容量计算', year:'2015',
        q:'某存储器芯片地址线 14 根、数据线 8 根，求其存储容量（以 KB 为单位）。',
        opts:[], ans:[], explain:'地址数=2^14=16K，数据线 8 位=1 字节，容量=16K×1B=16KB。' },
      { id:'co-05', type:'sc', tier:'拔高', chap:'流水线',
        q:'关于指令流水线，下列说法正确的是（ ）。',
        opts:['A. 流水线深度越大吞吐率一定越高','B. 流水线的实际吞吐率受最慢段（瓶颈）限制','C. 数据相关不会降低吞吐率','D. 流水线是空间并行技术'],
        ans:1, explain:'实际吞吐率受最慢功能段（瓶颈段）限制；深度过大因锁存开销反而可能下降；数据相关会引起停顿；流水线是时间并行（指令重叠）技术。' },
      { id:'co-06', type:'sa', tier:'创新', chap:'存储·Cache',
        q:'简述 Cache 的三种地址映射方式及其特点。',
        opts:[], ans:[], explain:'①直接映射：主存块固定映射到唯一 Cache 行，简单但冲突率高；②全相联：可映射到任意行，冲突率低但比较电路复杂；③组相联：折中，分组后组内全相联，兼顾性能与成本。' },
      { id:'co-07', type:'sc', tier:'基础', chap:'CPU·寄存器',
        q:'用于存放将要访问的内存单元地址的寄存器是（ ）。',
        opts:['A. MDR','B. MAR','C. PC','D. IR'],
        ans:1, explain:'MAR（存储器地址寄存器）存放访存地址；MDR 存数据；PC 存指令地址；IR 存指令本身。' },
      { id:'co-08', type:'fill', tier:'拔高', chap:'指令周期',
        q:'完成一条指令的全过程通常包含______周期、______周期、执行周期，间址与中断周期按需出现。',
        opts:[], ans:['取指','间址'], explain:'指令周期 = 取指周期 + 间址周期（可选）+ 执行周期 + 中断周期（可选）；最基础为取指+执行。' }
    ],

    /* ============================== 408 · 操作系统 ============================== */
    os: [
      { id:'os-01', type:'sc', tier:'基础', chap:'进程·状态',
        q:'进程的三种基本状态不包括（ ）。',
        opts:['A. 就绪态','B. 运行态','C. 挂起态','D. 阻塞态'],
        ans:2, explain:'进程三基本状态：就绪、运行、阻塞（等待）。挂起态不是基本状态（属扩展状态）。' },
      { id:'os-02', type:'mc', tier:'拔高', chap:'死锁',
        q:'产生死锁的必要条件包括（ ）。（多选）',
        opts:['A. 互斥','B. 占有并等待','C. 不可剥夺','D. 循环等待'],
        ans:[0,1,2,3], explain:'死锁四必要条件：互斥、占有并等待（请求和保持）、不可剥夺、循环等待。四项全选。' },
      { id:'os-03', type:'fill', tier:'基础', chap:'死锁·避免',
        q:'______算法是经典的死锁避免算法，通过安全性检查决定是否分配资源。',
        opts:[], ans:['银行家','banker','银行家算法'], explain:'银行家算法（Banker\'s Algorithm）在资源分配前进行安全性检查，避免系统进入不安全状态。' },
      { id:'os-04', type:'calc', tier:'真题风格', chap:'内存·页面置换', year:'2014',
        q:'某进程访问页号序列 1,2,3,1,2,4,1,2,3,4，物理块数为 3，采用 FIFO 置换，求缺页次数。',
        opts:[], ans:[], explain:'物理块3，FIFO：1(缺)→2(缺)→3(缺)→1(命中)→2(命中)→4(缺,换1)→1(缺,换2)→2(缺,换3)→3(缺,换4)→4(缺,换1)。缺页：1,2,3,4,1,2,3,4 共 9 次（注意第4次后 1,2 已在；第7次1不在块中→缺）。' },
      { id:'os-05', type:'sc', tier:'基础', chap:'内存·虚拟存储',
        q:'虚拟存储器得以实现的理论基础是（ ）。',
        opts:['A. 程序的顺序执行','B. 程序局部性原理','C. 多道程序设计','D. 时分复用'],
        ans:1, explain:'虚拟存储基于程序运行的局部性原理（时间局部性+空间局部性），使部分装入内存即可运行。' },
      { id:'os-06', type:'sa', tier:'拔高', chap:'调度',
        q:'简述处理机调度的几个层次（作业调度/内存调度/进程调度）及其主要职能。',
        opts:[], ans:[], explain:'①高级调度（作业调度）：决定哪些作业调入内存，频率低；②中级调度（内存调度/对换）：决定进程在内外存间换入换出，调活度高；③低级调度（进程调度/CPU调度）：决定哪个就绪进程获 CPU，频率最高。' },
      { id:'os-07', type:'sc', tier:'拔高', chap:'同步·信号量',
        q:'用信号量 P、V 操作实现临界区互斥，进入临界区前应执行（ ）。',
        opts:['A. V 操作','B. P 操作','C. 先 V 后 P','D. 无需操作'],
        ans:1, explain:'进入临界区前执行 P(S)（申请资源/减1），若 S<0 则阻塞；退出执行 V(S)（释放/加1）。' },
      { id:'os-08', type:'fill', tier:'创新', chap:'磁盘·调度',
        q:'磁盘调度中，______算法按请求到达顺序服务，公平但寻道时间长；______算法基于扫描臂单向移动。',
        opts:[], ans:['fcfs','scan','先来先服务','扫描'], explain:'FCFS（先来先服务）按到达顺序，简单公平但寻道可能很长；SCAN（扫描/电梯）算法使磁臂单向移动并服务途中请求。' }
    ],

    /* ============================== 408 · 计算机网络 ============================== */
    cn: [
      { id:'cn-01', type:'sc', tier:'基础', chap:'应用层·端口',
        q:'HTTP 协议默认使用的端口号是（ ）。',
        opts:['A. 21','B. 22','C. 80','D. 443'],
        ans:2, explain:'HTTP 默认端口 80；HTTPS 443；FTP 21；SSH 22。' },
      { id:'cn-02', type:'mc', tier:'拔高', chap:'传输层·TCP',
        q:'TCP 保证可靠传输的机制包括（ ）。（多选）',
        opts:['A. 序号与确认','B. 滑动窗口（流量控制）','C. 超时重传','D. 三次握手建立连接'],
        ans:[0,1,2,3], explain:'TCP 可靠传输依赖：序号+确认、滑动窗口（流量控制）、超时重传、三次握手（连接管理）等。四项均正确。' },
      { id:'cn-03', type:'fill', tier:'基础', chap:'网络层·IP',
        q:'TCP/IP 协议栈中，IP 层（网际层）的主要功能是______和逻辑寻址。',
        opts:[], ans:['路由选择','路由','寻址'], explain:'IP 层负责主机间数据报的路由选择（转发）与逻辑地址（IP 地址）寻址；可靠传输由上层 TCP 负责。' },
      { id:'cn-04', type:'calc', tier:'真题风格', chap:'网络层·子网划分', year:'2013',
        q:'将 192.168.1.0/24 划分为若干子网，要求每个子网至少 30 台主机，求子网掩码与可用子网数。',
        opts:[], ans:[], explain:'主机位需 ≥ log2(30+2)=5 位（含网络/广播），故主机位取 5，子网位=8−5=3 位。子网掩码 255.255.255.224（/27）。可用子网数=2^3−2=6 个（传统掐头去尾），每子网可用主机 30 台。' },
      { id:'cn-05', type:'sc', tier:'拔高', chap:'体系结构',
        q:'关于 OSI 参考模型与 TCP/IP 模型，下列说法正确的是（ ）。',
        opts:['A. OSI 只有 4 层','B. TCP/IP 严格对应 OSI 七层','C. OSI 是理论模型，TCP/IP 是工业事实标准','D. 两者层数完全相同'],
        ans:2, explain:'OSI 是理论上的七层参考模型；TCP/IP 是实际部署的工业标准（四层/五层划分），二者并非严格一一对应。' },
      { id:'cn-06', type:'sa', tier:'创新', chap:'传输层·连接管理',
        q:'简述 TCP 三次握手建立连接的过程，并说明为何需要三次而非两次。',
        opts:[], ans:[], explain:'①SYN：客户端发 SYN=1,seq=x；②SYN+ACK：服务端回 SYN=1,ACK=1,seq=y,ack=x+1；③ACK：客户端发 ACK=1,seq=x+1,ack=y+1。三次是为了双方都能确认“对方收发能力正常”；两次握手无法确认客户端收能力，且旧连接请求可能让服务端误建连接造成资源浪费。' },
      { id:'cn-07', type:'sc', tier:'基础', chap:'应用层·DNS',
        q:'域名系统 DNS 默认使用的端口与传输层协议组合是（ ）。',
        opts:['A. 53 / UDP','B. 53 / TCP','C. 80 / UDP','D. 25 / TCP'],
        ans:0, explain:'DNS 默认端口 53，查询一般用 UDP（高效），区域传送用 TCP。选项中 53/UDP 最标准。' },
      { id:'cn-08', type:'fill', tier:'基础', chap:'数据链路层·介质访问',
        q:'以太网采用______协议检测冲突并退避重发（CSMA/______）。',
        opts:[], ans:['csma/cd','载波侦听多路访问/冲突检测'], explain:'以太网采用 CSMA/CD（载波侦听多路访问/冲突检测）；无线局域网用 CSMA/CA。' }
    ],

    /* ============================== 自考 · 高等数学(工本) ============================== */
    gk: [
      { id:'gk-01', type:'sc', tier:'基础', chap:'极限·重要极限',
        q:'极限 lim(x→0) (e^x − 1 − x) / x² = （ ）。',
        opts:['A. 0','B. 1/2','C. 1','D. ∞'],
        ans:1, explain:'泰勒展开 e^x=1+x+x²/2+o(x²)，代入得 (x²/2)/x² → 1/2。' },
      { id:'gk-02', type:'calc', tier:'拔高', chap:'积分·不定积分',
        q:'求不定积分 ∫ x e^x dx。',
        opts:[], ans:[], explain:'分部积分：u=x, dv=e^x dx → ∫xe^x dx = xe^x − ∫e^x dx = (x−1)e^x + C。' },
      { id:'gk-03', type:'fill', tier:'基础', chap:'导数·定义',
        q:'函数 f(x) 在 x₀ 处可导的等价条件是极限 lim(Δx→0) ______ 存在。',
        opts:[], ans:['(f(x0+Δx)-f(x0))/Δx','(f(x0+h)-f(x0))/h'], explain:'导数定义 f\'(x₀)=lim(Δx→0)[f(x₀+Δx)−f(x₀)]/Δx。' },
      { id:'gk-04', type:'sc', tier:'真题风格', chap:'中值定理', year:'2022',
        q:'函数 f(x)=x³ 在 [0,1] 上满足拉格朗日中值定理，存在 ξ∈(0,1) 使 f\'(ξ) = （ ）。',
        opts:['A. 0','B. 1','C. 2','D. 3'],
        ans:1, explain:'拉格朗日中值定理：f\'(ξ)=[f(1)−f(0)]/(1−0)=(1−0)/1=1。' },
      { id:'gk-05', type:'calc', tier:'拔高', chap:'积分·定积分',
        q:'计算定积分 ∫_0^π x sin x dx。',
        opts:[], ans:[], explain:'∫x sin x dx = −x cos x + sin x，代入 [0,π]：(−π·(−1)+0)−0 = π。' },
      { id:'gk-06', type:'sa', tier:'基础', chap:'导数应用·极值',
        q:'求函数极值的导数判定法（第一充分条件）要点。',
        opts:[], ans:[], explain:'设 f\'(x₀)=0 或不存在（驻点/不可导点）。若 x 过 x₀ 时 f\' 由正变负，则 x₀ 为极大值点；由负变正则极小值点；不变号则非极值。' },
      { id:'gk-07', type:'mc', tier:'拔高', chap:'多元函数·偏导',
        q:'关于二元函数 z=f(x,y) 的偏导数，下列说法正确的有（ ）。（多选）',
        opts:['A. ∂z/∂x 是将 y 视为常数对 x 求导','B. 偏导数存在则函数必连续','C. 全微分存在要求偏导数连续','D. 混合偏导在连续条件下与次序无关'],
        ans:[0,3], explain:'A 正确（偏导定义）；D 正确（Clairaut 定理：混合偏导连续则相等）。B 错：偏导存在不保证连续；C 错：全微分存在只需偏导存在且满足线性近似，不必偏导连续（偏导连续是充分非必要）。' },
      { id:'gk-08', type:'sc', tier:'基础', chap:'导数应用·切线',
        q:'曲线 y=ln x 在点 (1,0) 处的切线方程是（ ）。',
        opts:['A. y=x−1','B. y=x+1','C. y=2x−2','D. y=x'],
        ans:0, explain:'y\'=1/x，x=1 处斜率为 1，切线 y−0=1·(x−1)，即 y=x−1。' }
    ],

    /* ============================== 自考 · 线性代数(工) ============================== */
    la: [
      { id:'la-01', type:'sc', tier:'基础', chap:'行列式',
        q:'矩阵 A = [[1,2],[3,4]] 的行列式 |A| = （ ）。',
        opts:['A. −2','B. 2','C. 6','D. −6'],
        ans:0, explain:'|A| = 1×4 − 2×3 = 4 − 6 = −2。' },
      { id:'la-02', type:'fill', tier:'基础', chap:'矩阵·秩',
        q:'设 A 为 3×4 矩阵，且齐次方程组 AX=0 只有零解，则 rank(A) = ______。',
        opts:[], ans:['4','四'], explain:'齐次方程组 AX=0 只有零解的充要条件是 rank(A)=列数=4（满列秩）。' },
      { id:'la-03', type:'mc', tier:'拔高', chap:'特征值',
        q:'关于矩阵特征值，下列说法正确的有（ ）。（多选）',
        opts:['A. 方阵必有实数特征值','B. 特征值之和等于矩阵的迹','C. 特征值之积等于行列式','D. 不同特征值对应的特征向量线性无关'],
        ans:[1,2,3], explain:'B、C 为特征值基本性质（∑λ_i=tr(A)，∏λ_i=|A|）；D 正确（不同特征值的特征向量线性无关）。A 错：实矩阵特征值可为复数（如旋转矩阵）。' },
      { id:'la-04', type:'calc', tier:'真题风格', chap:'线性方程组', year:'2021',
        q:'解线性方程组：x+y=3, 2x−y=0。求 x, y。',
        opts:[], ans:[], explain:'由 2x−y=0 得 y=2x；代入 x+2x=3 → 3x=3 → x=1，y=2。解为 (1,2)。' },
      { id:'la-05', type:'sc', tier:'基础', chap:'矩阵·正交',
        q:'若方阵 Q 满足 Q^T Q = I，则称 Q 为（ ）。',
        opts:['A. 对称矩阵','B. 正交矩阵','C. 可逆矩阵','D. 对角矩阵'],
        ans:1, explain:'Q^T Q=I（即 Q^{-1}=Q^T）的实方阵为正交矩阵，保持向量长度与夹角。' },
      { id:'la-06', type:'sa', tier:'拔高', chap:'对角化',
        q:'n 阶矩阵可相似对角化的充要条件是什么？简述要点。',
        opts:[], ans:[], explain:'充要条件：有 n 个线性无关的特征向量（等价于每个特征值的几何重数=代数重数）。实对称矩阵必可对角化且可正交对角化。' },
      { id:'la-07', type:'sc', tier:'创新', chap:'二次型·正定',
        q:'判定实对称矩阵正定的充分必要条件是（ ）。',
        opts:['A. 行列式大于 0','B. 各阶顺序主子式全大于 0','C. 迹大于 0','D. 特征值全为非负'],
        ans:1, explain:'Sylvester 定理：实对称矩阵正定 ⇔ 各阶顺序主子式全 > 0。A 仅末阶；C 不充分；D 为非负定。' },
      { id:'la-08', type:'fill', tier:'基础', chap:'行列式·展开',
        q:'行列式按第 i 行展开的公式是 D = Σ_{j=1}^n a_{ij}·______，其中空白处为代数余子式。',
        opts:[], ans:['aij','Aij'], explain:'按行展开：D=Σ a_{ij}·A_{ij}，A_{ij}=(−1)^{i+j}M_{ij} 为代数余子式。' }
    ]
  }
};
